dcConsData = [
	{name:"소닉링없찐.gif", 	keywords:["링없찐"], tags:["소닉", "소닉매니아"]},
	{name:"소닉결혼반지.png",	keywords:["결혼반지"], tags:["소닉", "소닉매니아"]},
	{name:"머니앵무.gif",	keywords:["머니앵무", "돈앵무"],	tags:["앵무"]},
	{name:"소라고둥.png",	keywords:["소라고둥"],	tags:["스폰지밥"]},
            {name:"F.gif",	keywords:["F", "f", "파이어"],	tags:["스폰지밥"]},
            {name:"혼란앵무.gif",	keywords:["혼란앵무"],	tags:["앵무"]},
            {name:"더블앵무.gif",	keywords:["더블앵무"],	tags:["앵무"]},
            {name:"기타댕댕.gif",	keywords:["댕댕콘"],	tags:["시바견"]},
            {name:"기타매우정상.png",	keywords:["매우정상"],	tags:["바람의나라"]},
            {name:"기타상담필요.png",	keywords:["상담필요"],	tags:["바람의나라"]},
            {name:"기타힘의차이.png",	keywords:["힘의차이"],	tags:["그림"]},
            {name:"나무꺼라.png",	keywords:["꺼라"],	            tags:["나무위키"]},
            {name:"나무켜라.png",	keywords:["켜라"],	            tags:["나무위키"]},
            {name:"레바설명.png",	keywords:["설명들갑", "레바설명"],	tags:["레바"]},
            {name:"레바에라.png",	keywords:["에라몰겠", "모르겠당"],	tags:["레바"]},
            {name:"레바이제좀.png",	keywords:["볼만", "볼만하네"],	tags:["레바"]},
            {name:"레바탕탕.gif",	keywords:["탕탕", "레바탕탕"],	tags:["레바"]},
            {name:"벤브꼬우면.gif",	keywords:["꼬우면"],	tags:["벤브"]},
            {name:"벤브버그.gif",	keywords:["버그", "대부분"],	tags:["벤브"]},
            {name:"벤브의도.gif",	keywords:["의도된", "의도"],	tags:["벤브"]},
            {name:"샌즈.png",        	keywords:["샌즈", "와"],	tags:["샌즈"]},
            {name:"손님멀미1.gif",	keywords:["멀미1"],	            tags:["롤코타"]},
            {name:"손님멀미2.gif",	keywords:["멀미2"],	            tags:["롤코타"]},
            {name:"손님멀미3.gif",	keywords:["멀미3"],	            tags:["롤코타"]},
            {name:"손님무표정.gif",	keywords:["무표정"],	tags:["롤코타"]},
            {name:"손님불행1.gif",	keywords:["화남1"],	            tags:["롤코타"]},
            {name:"손님불행2.gif",	keywords:["화남2"],	            tags:["롤코타"]},
            {name:"손님빨갱이.gif",	keywords:["빨강손님", "매우화남"],	            tags:["롤코타"]},
            {name:"손님행복1.gif",	keywords:["행복1"],	            tags:["롤코타"]},
            {name:"손님행복2.gif",	keywords:["행복2"],	            tags:["롤코타"]},
            {name:"롤코화장실.gif",	keywords:["화장실"],	            tags:["롤코타"]},
            {name:"캐피탈노예일해.png",	keywords:["노예일해"],	            tags:["캐피"]},
            {name:"캐피탈퍄산.png",	keywords:["파산"],	            tags:["캐피"]},
            {name:"캐피탈폴짝.png",	keywords:["폴짝"],	            tags:["캐피"]},
            {name:"케피탈이지붐.gif",	keywords:["이지붐"],	tags:["캐피"]},
            {name:"텃다.png",	            keywords:["텃다"],	            tags:["원숭이"]},
            {name:"핫산발상.png",	keywords:["핫산발상"],	            tags:["핫산"]},
            {name:"핫산쾅.png",	keywords:["핫산쾅"],	            tags:["핫산"]},
            {name:"핫산펑.png",	keywords:["핫산펑"],	            tags:["핫산"]},
            {name:"흠.png",	keywords:["흠"],	            tags:["표정"]},
            {name:"핑구박수.gif",	keywords:["핑구박수"],	tags:["핑구"]}
];